# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'showTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for showTime

  target 'showTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'showTimeUITests' do
    # Pods for testing
  end

end
